version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: America/Bogota
    open-pull-requests-limit: 5
    groups:
      menores:
        update-types: [minor, patch]
    labels: [dependencias]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencias]
